name: tenant
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  firebase_core: ^0.4.5
  firebase_database: ^3.1.6
  firebase_storage: ^3.1.5
  connectivity: ^0.4.8+2
  fluttertoast: ^4.0.1
  google_fonts: ^1.0.0
  flutter_spinkit: ^3.1.0
  url_launcher: ^5.4.10
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
